fn relationship_name(raw: &str) -> String {
    let cleaned = raw
        .trim()
        .trim_start_matches("Custom(")
        .trim_end_matches(')')
        .replace([' ', '-', '_'], "");

    match cleaned.to_ascii_lowercase().as_str() {
        "memberof" => "MemberOf",
        "adminto" | "localadmins" => "AdminTo",
        "hassession" | "sessions" => "HasSession",
        "canrdp" | "rdpusers" | "remotedesktopusers" => "CanRDP",
        "canpsremote" | "psremoteusers" => "CanPSRemote",
        "executedcom" | "dcomusers" => "ExecuteDCOM",
        "sqladmin" | "sqladminusers" => "SQLAdmin",
        "genericall" => "GenericAll",
        "genericwrite" => "GenericWrite",
        "writeowner" => "WriteOwner",
        "writedacl" => "WriteDacl",
        "forcechangepassword" => "ForceChangePassword",
        "addmembers" => "AddMembers",
        "addself" => "AddSelf",
        "readlapspassword" => "ReadLapsPassword",
        "readgmsapassword" => "ReadGmsaPassword",
        "allowedtodelegate" => "AllowedToDelegate",
        "allowedtoact" => "AllowedToAct",
        "hassidhistory" => "HasSidHistory",
        "dcsync" => "DcSync",
        "getchanges" => "GetChanges",
        "getchangesall" => "GetChangesAll",
        "trustedby" | "trusts" => "TrustedBy",
        "hasspn" | "spntargets" => "HasSpn",
        "dontreqpreauth" => "DontReqPreauth",
        "gpolink" | "links" | "gpochanges" => "GpoLink",
        "contains" | "childobjects" => "Contains",
        "owns" => "Owns",
        // ── Attribute-level WriteProperty edges ─────────────────────────────────
        "writespn" => "WriteSPN",
        "writeallowedtodelegateto" => "WriteAllowedToDelegateTo",
        "addallowedtoact" => "AddAllowedToAct",
        "writeaccountrestrictions" => "WriteAccountRestrictions",
        "writelogonScript" => "WriteLogonScript",
        "writeprofilepath" => "WriteProfilePath",
        "writescriptpath" => "WriteScriptPath",
        "writednshostname" => "WriteDnsHostName",
        "writeserviceprincipalname" => "WriteServicePrincipalName",
        "writekeycredentialLink" => "WriteKeyCredentialLink",
        "writemsdskeycredentialLink" => "WriteMsDsKeyCredentialLink",
        "writealtsecurityidentities" => "WriteAltSecurityIdentities",
        "writeuserparameters" => "WriteUserParameters",
        "writepwdproperties" => "WritePwdProperties",
        "writelockoutthreshold" => "WriteLockoutThreshold",
        "writeminpwdlength" => "WriteMinPwdLength",
        "writepwdhistorylength" => "WritePwdHistoryLength",
        "writepwdcomplexity" => "WritePwdComplexity",
        "writepwdreversibleencryption" => "WritePwdReversibleEncryption",
        "writepwdage" => "WritePwdAge",
        "writelockoutduration" => "WriteLockoutDuration",
        "writelockoutobservationwindow" => "WriteLockoutObservationWindow",
        "writegplink" => "WriteGPLink",
        "addkeycredentialLink" => "AddKeyCredentialLink",
        "writeproperty" => "WriteProperty",
        "" => "Relationship",
        _ => cleaned,
    }
    .to_string()
}
