fn edge_color(edge_type: &EdgeType, highlighted: bool) -> Color {
    if highlighted {
        return Color::LightRed;
    }
    match edge_type {
        EdgeType::MemberOf => Color::DarkGray,
        EdgeType::AdminTo => Color::Red,
        EdgeType::HasSession => Color::Yellow,
        EdgeType::CanRDP => Color::Cyan,
        EdgeType::CanPSRemote => Color::Blue,
        EdgeType::GenericAll => Color::LightRed,
        EdgeType::WriteDacl => Color::LightRed,
        EdgeType::WriteOwner => Color::LightRed,
        EdgeType::DcSync => Color::Magenta,
        EdgeType::TrustedBy => Color::LightMagenta,
        EdgeType::Contains => Color::DarkGray,
        // ── Attribute-level WriteProperty edges ─────────────────────────────────
        EdgeType::WriteSPN => Color::Yellow,
        EdgeType::WriteAllowedToDelegateTo => Color::Magenta,
        EdgeType::AddAllowedToAct => Color::Red,
        EdgeType::WriteAccountRestrictions => Color::Yellow,
        EdgeType::WriteLogonScript => Color::Green,
        EdgeType::WriteProfilePath => Color::Green,
        EdgeType::WriteScriptPath => Color::Green,
        EdgeType::WriteDnsHostName => Color::Cyan,
        EdgeType::WriteServicePrincipalName => Color::Yellow,
        EdgeType::WriteKeyCredentialLink => Color::Magenta,
        EdgeType::WriteMsDsKeyCredentialLink => Color::Magenta,
        EdgeType::WriteAltSecurityIdentities => Color::Magenta,
        EdgeType::WriteUserParameters => Color::Blue,
        EdgeType::WritePwdProperties => Color::Red,
        EdgeType::WriteLockoutThreshold => Color::Red,
        EdgeType::WriteMinPwdLength => Color::Red,
        EdgeType::WritePwdHistoryLength => Color::Red,
        EdgeType::WritePwdComplexity => Color::Red,
        EdgeType::WritePwdReversibleEncryption => Color::Red,
        EdgeType::WritePwdAge => Color::Red,
        EdgeType::WriteLockoutDuration => Color::Red,
        EdgeType::WriteLockoutObservationWindow => Color::Red,
        EdgeType::WriteGPLink => Color::Green,
        EdgeType::AddKeyCredentialLink => Color::Magenta,
        EdgeType::WriteProperty { .. } => Color::LightYellow,
        _ => Color::Gray,
    }
}
