//! Markdown report renderer — Produces a complete pentest report
//! in Markdown format suitable for conversion to HTML/PDF or
//! direct rendering in documentation platforms.

use crate::mapper;
use crate::narrative;
use crate::session::{EngagementSession, EvidenceType, Finding, Severity};
use chrono::Utc;

/// Render a complete Markdown report from the session
pub fn render(session: &EngagementSession) -> String {
    let mut md = String::with_capacity(32_768);

    // ── Title Page ──
    render_title_page(&mut md, session);

    // ── Table of Contents ──
    render_toc(&mut md, session);

    // ── Executive Summary ──
    md.push_str("---\n\n## 1. Executive Summary\n\n");
    md.push_str(&narrative::executive_summary(session));
    md.push_str("\n\n");
    render_severity_table(&mut md, session);

    // ── Scope ──
    md.push_str("---\n\n## 2. Scope & Objectives\n\n");
    md.push_str(&narrative::scope_description(session));
    md.push_str("\n\n");

    // ── Methodology ──
    md.push_str("---\n\n## 3. Methodology\n\n");
    md.push_str(&narrative::methodology_description());
    md.push_str("\n\n");

    // ── Findings ──
    md.push_str("---\n\n## 4. Findings\n\n");
    if session.findings.is_empty() {
        md.push_str("No findings were identified during the assessment.\n\n");
    } else {
        render_findings_summary_table(&mut md, session);
        for (i, finding) in session.findings.iter().enumerate() {
            render_finding(&mut md, finding, i + 1);
        }
    }

    // ── Attack Chain ──
    md.push_str("---\n\n## 5. Attack Chain\n\n");
    md.push_str(&narrative::attack_chain_narrative(session));
    md.push_str("\n\n");

    // ── MITRE ATT&CK Mapping ──
    md.push_str("---\n\n## 6. MITRE ATT&CK Mapping\n\n");
    render_mitre_matrix(&mut md, session);

    // ── Remediation Roadmap ──
    md.push_str("---\n\n## 7. Remediation Roadmap\n\n");
    render_remediation_roadmap(&mut md, session);

    // ── Domain Statistics ──
    md.push_str("---\n\n## 8. Domain Statistics\n\n");
    render_domain_stats(&mut md, session);

    // ── Appendix: Action Log ──
    md.push_str("---\n\n## Appendix A: Full Action Log\n\n");
    render_action_log(&mut md, session);

    // ── Footer ──
    md.push_str("---\n\n");
    md.push_str(&format!(
        "*Report generated by Overthrone Scribe v{} on {}*\n",
        env!("CARGO_PKG_VERSION"),
        Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));

    md
}

// ═══════════════════════════════════════════════════════════
// Section Renderers
// ═══════════════════════════════════════════════════════════

fn render_title_page(md: &mut String, session: &EngagementSession) {
    md.push_str(&format!("# {}\n\n", session.title));
    md.push_str(&format!("**Classification:** {}\n\n", session.classification));
    md.push_str("| | |\n|---|---|\n");
    md.push_str(&format!("| **Client** | {} |\n", session.client_name));
    md.push_str(&format!("| **Assessor** | {} ({}) |\n", session.assessor_name, session.assessor_company));
    md.push_str(&format!("| **Engagement Type** | {} |\n", session.engagement_type));
    md.push_str(&format!(
        "| **Assessment Period** | {} — {} |\n",
        session.started_at.format("%Y-%m-%d"),
        session
            .finished_at
            .map(|d| d.format("%Y-%m-%d").to_string())
            .unwrap_or_else(|| "Ongoing".to_string())
    ));
    md.push_str(&format!("| **Report Version** | {} |\n", session.version));
    md.push_str(&format!("| **Report ID** | {} |\n", session.id));
    md.push_str(&format!(
        "| **Overall Risk** | **{}** |\n",
        session.overall_risk()
    ));
    md.push_str("\n\n");
}

fn render_toc(md: &mut String, session: &EngagementSession) {
    md.push_str("## Table of Contents\n\n");
    md.push_str("1. [Executive Summary](#1-executive-summary)\n");
    md.push_str("2. [Scope & Objectives](#2-scope--objectives)\n");
    md.push_str("3. [Methodology](#3-methodology)\n");
    md.push_str("4. [Findings](#4-findings)\n");
    for (i, f) in session.findings.iter().enumerate() {
        md.push_str(&format!(
            "   - 4.{} [{}](#finding-{})\n",
            i + 1,
            f.title,
            i + 1
        ));
    }
    md.push_str("5. [Attack Chain](#5-attack-chain)\n");
    md.push_str("6. [MITRE ATT&CK Mapping](#6-mitre-attck-mapping)\n");
    md.push_str("7. [Remediation Roadmap](#7-remediation-roadmap)\n");
    md.push_str("8. [Domain Statistics](#8-domain-statistics)\n");
    md.push_str("- [Appendix A: Full Action Log](#appendix-a-full-action-log)\n");
    md.push_str("\n\n");
}

fn render_severity_table(md: &mut String, session: &EngagementSession) {
    let counts = session.severity_counts();
    md.push_str("### Findings by Severity\n\n");
    md.push_str("| Severity | Count |\n|---|---|\n");
    for sev in &[
        Severity::Critical,
        Severity::High,
        Severity::Medium,
        Severity::Low,
        Severity::Informational,
    ] {
        let count = counts.get(sev).copied().unwrap_or(0);
        if count > 0 {
            md.push_str(&format!("| **{}** | {} |\n", sev, count));
        }
    }
    md.push_str(&format!(
        "| **Total** | **{}** |\n\n",
        session.findings.len()
    ));
}

fn render_findings_summary_table(md: &mut String, session: &EngagementSession) {
    md.push_str("### Findings Overview\n\n");
    md.push_str("| # | ID | Title | Severity | CVSS |\n|---|---|---|---|---|\n");
    for (i, f) in session.findings.iter().enumerate() {
        md.push_str(&format!(
            "| {} | {} | {} | {} | {:.1} |\n",
            i + 1,
            f.id,
            f.title,
            f.severity,
            f.cvss_score
        ));
    }
    md.push('\n');
}

fn render_finding(md: &mut String, finding: &Finding, num: usize) {
    md.push_str(&format!(
        "### <a id=\"finding-{}\"></a>4.{} {} — {}\n\n",
        num, num, finding.id, finding.title
    ));

    // Metadata table
    md.push_str("| | |\n|---|---|\n");
    md.push_str(&format!("| **Severity** | {} |\n", finding.severity));
    md.push_str(&format!("| **CVSS Score** | {:.1} |\n", finding.cvss_score));
    if let Some(ref vec) = finding.cvss_vector {
        md.push_str(&format!("| **CVSS Vector** | `{}` |\n", vec));
    }
    md.push_str(&format!("| **Category** | {} |\n", finding.category));
    md.push('\n');

    // Description
    md.push_str("#### Description\n\n");
    md.push_str(&narrative::finding_narrative(finding));
    md.push_str("\n\n");

    // Affected assets
    if !finding.affected_assets.is_empty() {
        md.push_str("#### Affected Assets\n\n");
        for asset in &finding.affected_assets {
            md.push_str(&format!("- `{}`\n", asset));
        }
        md.push('\n');
    }

    // Proof of Concept
    if !finding.proof_of_concept.is_empty() {
        md.push_str("#### Proof of Concept\n\n");
        for (i, step) in finding.proof_of_concept.iter().enumerate() {
            md.push_str(&format!("{}. {}\n", i + 1, step));
        }
        md.push('\n');
    }

    // Evidence
    if !finding.evidence.is_empty() {
        md.push_str("#### Evidence\n\n");
        for ev in &finding.evidence {
            md.push_str(&format!("**{}** ({:?})\n\n", ev.label, ev.content_type));
            // Redact actual credential values
            let display = if ev.content_type == EvidenceType::Credential {
                "[REDACTED — see secure appendix]".to_string()
            } else if ev.content.len() > 500 {
                format!("{}…\n\n*(truncated — {} total characters)*", &ev.content[..500], ev.content.len())
            } else {
                ev.content.clone()
            };
            md.push_str(&format!("```\n{}\n```\n\n", display));
        }
    }

    // MITRE mapping
    if !finding.mitre.is_empty() {
        md.push_str("#### MITRE ATT&CK\n\n");
        for m in &finding.mitre {
            md.push_str(&format!(
                "- **{}** — {} (*{}*)\n",
                m.technique_id, m.technique_name, m.tactic
            ));
        }
        md.push('\n');
    }

    // Mitigations
    if !finding.mitigations.is_empty() {
        md.push_str("#### Recommendations\n\n");
        for mit in &finding.mitigations {
            md.push_str(&format!(
                "- **{}** [{}] [Effort: {}]\n  {}\n\n",
                mit.title, mit.priority, mit.effort, mit.description
            ));
        }
    }

    // References
    if !finding.references.is_empty() {
        md.push_str("#### References\n\n");
        for r in &finding.references {
            md.push_str(&format!("- {}\n", r));
        }
        md.push('\n');
    }
}

fn render_mitre_matrix(md: &mut String, session: &EngagementSession) {
    let matrix = mapper::build_attack_matrix(&session.findings);

    if matrix.is_empty() {
        md.push_str("No MITRE ATT&CK mappings applicable.\n\n");
        return;
    }

    md.push_str("| Tactic | Techniques |\n|---|---|\n");
    for (tactic, techniques) in &matrix {
        let techs: Vec<String> = techniques
            .iter()
            .map(|t| {
                match &t.sub_technique_id {
                    Some(sub) => format!("{}/{} ({})", t.technique_id, sub, t.technique_name),
                    None => format!("{} ({})", t.technique_id, t.technique_name),
                }
            })
            .collect();
        md.push_str(&format!("| **{}** | {} |\n", tactic, techs.join(", ")));
    }
    md.push('\n');
}

fn render_remediation_roadmap(md: &mut String, session: &EngagementSession) {
    let finding_types: Vec<&str> = session
        .findings
        .iter()
        .map(|f| match f.category {
            crate::session::FindingCategory::KerberosAbuse => "kerberoast",
            crate::session::FindingCategory::CredentialExposure => "credential_exposure",
            crate::session::FindingCategory::DelegationAbuse => "unconstrained_delegation",
            crate::session::FindingCategory::LateralMovement => "admin_access",
            crate::session::FindingCategory::PrivilegeEscalation => "domain_compromise",
            _ => "credential_exposure",
        })
        .collect();

    let mitigations = crate::mitigations::aggregate_mitigations(&finding_types);

    if mitigations.is_empty() {
        md.push_str("No specific remediation recommendations.\n\n");
        return;
    }

    md.push_str("| Priority | Recommendation | Category | Effort |\n|---|---|---|---|\n");
    for mit in &mitigations {
        md.push_str(&format!(
            "| {} | **{}** | {} | {} |\n",
            mit.priority, mit.title, mit.category, mit.effort
        ));
    }
    md.push('\n');

    // Expanded descriptions
    md.push_str("### Detailed Recommendations\n\n");
    for (i, mit) in mitigations.iter().enumerate() {
        md.push_str(&format!(
            "**{}.** {} [{}]\n\n{}\n\n",
            i + 1,
            mit.title,
            mit.priority,
            mit.description
        ));
    }
}

fn render_domain_stats(md: &mut String, session: &EngagementSession) {
    md.push_str("| Metric | Value |\n|---|---|\n");
    md.push_str(&format!(
        "| Users Enumerated | {} |\n",
        session.total_users_enumerated
    ));
    md.push_str(&format!(
        "| Computers Enumerated | {} |\n",
        session.total_computers_enumerated
    ));
    md.push_str(&format!(
        "| Credentials Compromised | {} |\n",
        session.total_credentials_compromised
    ));
    md.push_str(&format!(
        "| Hosts with Admin Access | {} |\n",
        session.total_admin_hosts
    ));
    md.push_str(&format!(
        "| Domain Admin Achieved | {} |\n",
        if session.domain_admin_achieved {
            "**YES**"
        } else {
            "No"
        }
    ));

    if let Some(ref state) = session.engagement_state {
        md.push_str(&format!(
            "| Kerberoastable Accounts | {} |\n",
            state.kerberoastable.len()
        ));
        md.push_str(&format!(
            "| AS-REP Roastable | {} |\n",
            state.asrep_roastable.len()
        ));
        md.push_str(&format!(
            "| Unconstrained Delegation | {} |\n",
            state.unconstrained_delegation.len()
        ));
    }
    md.push('\n');
}

fn render_action_log(md: &mut String, session: &EngagementSession) {
    let state = match &session.engagement_state {
        Some(s) => s,
        None => {
            md.push_str("No action log available.\n\n");
            return;
        }
    };

    if state.action_log.is_empty() {
        md.push_str("No actions were logged.\n\n");
        return;
    }

    md.push_str("| Time | Stage | Action | Result | Detail |\n|---|---|---|---|---|\n");
    for entry in &state.action_log {
        let detail_short = if entry.detail.len() > 60 {
            format!("{}…", &entry.detail[..57])
        } else {
            entry.detail.clone()
        };
        md.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            entry.timestamp.format("%H:%M:%S"),
            entry.stage,
            entry.action,
            if entry.success { "✓" } else { "✗" },
            detail_short
        ));
    }
    md.push('\n');
}
